package Seuranta.test;
// Generated by ComTest BEGIN
import Seuranta.*;
import java.util.*;
import java.io.File;
import java.io.IOException;
import java.util.NoSuchElementException;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.24 22:33:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreenitTest {



  // Generated by ComTest BEGIN
  /** testIterator46 */
  @Test
  public void testIterator46() {    // Treenit: 46
    Treenit treenit = new Treenit(); 
    Treeni pull = new Treeni(); treenit.lisaaTreeni(pull); 
    Treeni pull2 = new Treeni(); treenit.lisaaTreeni(pull2); 
    Iterator<Treeni> treeni2 = treenit.iterator(); 
    assertEquals("From: Treenit line: 55", pull, treeni2.next()); 
    assertEquals("From: Treenit line: 56", pull2, treeni2.next()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLue94 
   * @throws TallennusException when error
   * @throws IOException when error
   * @throws NoSuchElementException when error
   */
  @Test
  public void testLue94() throws TallennusException, IOException, NoSuchElementException {    // Treenit: 94
    Treenit treenit = new Treenit(); 
    Treeni selka = new Treeni(), jalat = new Treeni(); 
    selka.taytaSelkaTreenilla(1); 
    jalat.taytaSelkaTreenilla(1); 
    String tiedosto = "testitreenit"; 
    File ftied = new File(tiedosto + ".dat"); 
    ftied.delete(); 
    try {
    treenit.lue(tiedosto); 
    fail("Treenit: 109 Did not throw TallennusException");
    } catch(TallennusException _e_){ _e_.getMessage(); }
    treenit.lisaaTreeni(selka); 
    treenit.lisaaTreeni(jalat); 
    treenit.tallenna(); 
    treenit = new Treenit(); 
    treenit.lue(tiedosto); 
    Iterator<Treeni> i = treenit.iterator(); 
    assertEquals("From: Treenit line: 116", selka.toString(), i.next().toString()); 
    try {
    assertEquals("From: Treenit line: 117", jalat.toString(), i.next().toString()); 
    fail("Treenit: 117 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    assertEquals("From: Treenit line: 118", false, i.hasNext()); 
    assertEquals("From: Treenit line: 119", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeTreenit184 */
  @Test
  public void testHaeTreenit184() {    // Treenit: 184
    Treenit treenit = new Treenit(); 
    Treeni pull1 = new Treeni(); 
    pull1.taytaSelkaTreenilla(1); 
    treenit.lisaaTreeni(pull1); 
    Treeni pull2 = new Treeni(); 
    pull2.taytaSelkaTreenilla(2); 
    treenit.lisaaTreeni(pull2); 
    List<Treeni> loyty; 
    loyty = treenit.haeTreenit(1); 
    assertEquals("From: Treenit line: 199", 1, loyty.size()); 
    loyty = treenit.haeTreenit(2); 
    assertEquals("From: Treenit line: 201", 1, loyty.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaUniTreenit244 */
  @Test
  public void testPoistaUniTreenit244() {    // Treenit: 244
    Treenit treenit = new Treenit(); 
    Treeni tr1 = new Treeni(); tr1.taytaSelkaTreenilla(1); 
    Treeni tr2 = new Treeni(); tr2.taytaSelkaTreenilla(2); 
    Treeni tr3 = new Treeni(); tr3.taytaSelkaTreenilla(1); 
    treenit.lisaaTreeni(tr1); 
    treenit.lisaaTreeni(tr2); 
    treenit.lisaaTreeni(tr3); 
    assertEquals("From: Treenit line: 255", 2, treenit.poistaUniTreenit(1)); assertEquals("From: Treenit line: 255", 1, treenit.getTreenitMaara()); 
    assertEquals("From: Treenit line: 256", 0, treenit.poistaUniTreenit(3)); assertEquals("From: Treenit line: 256", 1, treenit.getTreenitMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista303 
   * @throws TallennusException when error
   */
  @Test
  public void testPoista303() throws TallennusException {    // Treenit: 303
    Treenit treenit = new Treenit(); 
    Treeni tr1 = new Treeni(); tr1.taytaSelkaTreenilla(1); 
    Treeni tr2 = new Treeni(); tr2.taytaSelkaTreenilla(2); 
    Treeni tr3 = new Treeni(); tr3.taytaSelkaTreenilla(1); 
    treenit.lisaaTreeni(tr1); 
    treenit.lisaaTreeni(tr2); 
    treenit.lisaaTreeni(tr3); 
    assertEquals("From: Treenit line: 316", true, treenit.poista(tr3)); assertEquals("From: Treenit line: 316", 2, treenit.getTreenitMaara()); 
    assertEquals("From: Treenit line: 317", true, treenit.poista(tr1)); assertEquals("From: Treenit line: 317", 1, treenit.getTreenitMaara()); 
  } // Generated by ComTest END
}