package Seuranta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Seuranta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 22:48:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreeniTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi145 */
  @Test
  public void testRekisteroi145() {    // Treeni: 145
    Treeni selka = new Treeni(); 
    assertEquals("From: Treeni line: 147", 0, selka.getTreeniNro()); 
    selka.rekisteroi(); 
    Treeni jalka = new Treeni(); 
    jalka.rekisteroi(); 
    int t1 = selka.getTreeniNro(); 
    int t2 = jalka.getTreeniNro(); 
    assertEquals("From: Treeni line: 154", t2 - 1, t1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse167 */
  @Test
  public void testParse167() {    // Treeni: 167
    Treeni treeni = new Treeni(); 
    treeni.parse("1|1|mave|180"); 
    assertEquals("From: Treeni line: 170", 1, treeni.getTreeniNro()); 
    assertEquals("From: Treeni line: 172", "1|1|mave|180.0||", treeni.toString()); 
    treeni.rekisteroi(); 
    int numero = treeni.getTreeniNro(); 
    treeni.parse(""+(numero+20)); 
    treeni.rekisteroi(); 
    treeni.getTreeniNro(); 
    assertEquals("From: Treeni line: 180", "" + (numero+20+1) + "|1|mave|180.0||", treeni.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString198 */
  @Test
  public void testToString198() {    // Treeni: 198
    Treeni treeni = new Treeni(); 
    treeni.parse(" 1 | 1 | mave | 180.0 | 4x3 | hyvin |"); 
    assertEquals("From: Treeni line: 201", "1|1|mave|180.0|4x3|hyvin", treeni.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta248 */
  @Test
  public void testAseta248() {    // Treeni: 248
    Treeni treeni = new Treeni(); 
    assertEquals("From: Treeni line: 250", null, treeni.aseta(2, "mave")); 
    assertEquals("From: Treeni line: 251", "Sarjapaino ei ole kokonaisluku (paino)", treeni.aseta(3, "paino")); 
    assertEquals("From: Treeni line: 252", null, treeni.aseta(5, "kiva")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone292 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone292() throws CloneNotSupportedException {    // Treeni: 292
    Treeni treeni = new Treeni(); 
    treeni.parse("1|1|mave|180.0|3x1|kiva"); 
    Treeni treeni2 = treeni.clone(); 
    assertEquals("From: Treeni line: 297", treeni.toString(), treeni2.toString()); 
    treeni.parse("2|2|pena|120.0|4x1|kivaaaa"); 
    assertEquals("From: Treeni line: 299", false, treeni2.toString().equals(treeni.toString())); 
  } // Generated by ComTest END
}