package tietuepaketti.test;
// Generated by ComTest BEGIN
import Seuranta.Treeni;
import static org.junit.Assert.*;
import org.junit.*;
import tietuepaketti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 23:12:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietueTest {



  // Generated by ComTest BEGIN
  /** testInt14 */
  @Test
  public void testInt14() {    // Tietue: 14
    Treeni treeni = new Treeni(); 
    assertEquals("From: Tietue line: 17", 6, treeni.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt25 */
  @Test
  public void testInt25() {    // Tietue: 25
    Treeni treeni = new Treeni(); 
    assertEquals("From: Tietue line: 28", 2, treeni.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString38 */
  @Test
  public void testString38() {    // Tietue: 38
    Treeni treeni = new Treeni(); 
    assertEquals("From: Tietue line: 41", "Paino", treeni.getKysymys(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString50 */
  @Test
  public void testString50() {    // Tietue: 50
    Treeni treeni = new Treeni(); 
    treeni.parse("1|1|mave|180|3x1|kiva"); 
    assertEquals("From: Tietue line: 53", "1", treeni.anna(0)); 
    assertEquals("From: Tietue line: 54", "1", treeni.anna(1)); 
    assertEquals("From: Tietue line: 55", "mave", treeni.anna(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString65 */
  @Test
  public void testString65() {    // Tietue: 65
    Treeni treeni = new Treeni(); 
    assertEquals("From: Tietue line: 67", null, treeni.aseta(2, "mave")); 
    assertEquals("From: Tietue line: 68", "Sarjapaino ei ole kokonaisluku (paino)", treeni.aseta(3, "paino")); 
    assertEquals("From: Tietue line: 69", null, treeni.aseta(5, "kiva")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTietue80 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testTietue80() throws CloneNotSupportedException {    // Tietue: 80
    Treeni treeni = new Treeni(); 
    treeni.parse("1|1|mave|180.0|3x1|kiva"); 
    Treeni treeni2 = treeni.clone(); 
    assertEquals("From: Tietue line: 85", treeni.toString(), treeni2.toString()); 
    treeni.parse("2|2|pena|120.0|4x1|kivaaaa"); 
    assertEquals("From: Tietue line: 87", false, treeni2.toString().equals(treeni.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString96 */
  @Test
  public void testString96() {    // Tietue: 96
    Treeni treeni = new Treeni(); 
    treeni.parse(" 1 | 1 | mave | 180.0 | 4x3 | hyvin |"); 
    assertEquals("From: Tietue line: 99", "1|1|mave|180.0|4x3|hyvin", treeni.toString()); 
  } // Generated by ComTest END
}